### ISSUE TITLE
passthrough server does not implements messageSelfAndDeferRetirement correctly

### ISSUE THREAD

**Issue by AbfrmBlr** [Terracotta-OSS/tc-passthrough-testing#23]
See `messageSelfAndDeferRetirement` in `PassthroughMessengerService`

**Comment by jd0-sag** [comment]
To flesh this out a bit more, the implementation of `messageSelf` includes some additional logic (of most obvious importance is `PassthroughMessageCodec.createInvokeMessage`) that is conspicuously absent from `messageSelfAndDeferRetirement`.

We will need to take some time to look at this and see if this missing call is the only problem in the logic.
