### ISSUE TITLE
Timeout issues when using MacOS Sierra and IPv6

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/tc-passthrough-testing#49]
I just upgraded to MacOS Sierra and all test using passthrough server timeout. I finally found the origin stack trace:

```
test_expose(org.terracotta.management.entity.management.ManagementAgentServiceTest)  Time elapsed: 20.344 sec  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 5000 milliseconds
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1500)
	at org.terracotta.passthrough.PassthroughServerProcess.connectConnection(PassthroughServerProcess.java:961)
	at org.terracotta.passthrough.PassthroughServer.connectNewClient(PassthroughServer.java:116)
	at org.terracotta.passthrough.PassthroughConnectionService.connect(PassthroughConnectionService.java:62)
	at org.terracotta.connection.ConnectionFactory.connect(ConnectionFactory.java:43)
	at org.terracotta.management.entity.management.ManagementAgentServiceTest.test_expose(ManagementAgentServiceTest.java:123)
```

Also:

```
➜  terracotta-platform git:(issue-178) ✗ cat /etc/hosts
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1       matc.local
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost 
```

I think something has changed in Sierra concerning the ip stack settings that cause timeouts when connecting to uris like:

`passthrough://localhost:9510/`.

Yesterday, I had the problem when connecting the TMS to a real voltron server by using: `terracotta://localhost:9510` or `terracotta://127.0.0.1:9510`. I had to disable the firewall (weird on the local interface)

**Comment by jd0-sag** [comment]
If you look at the stack trace you posted, the hang is in `java.net.InetAddress.getLocalHost`.  The passthrough server doesn't create any connections through the network stack.  The only reason why it is asking for localhost data is to generate some of the fake data for `PlatformConnectedClient`.

This is a known issue with Sierra which appears to be resolved by fiddling with the `/etc/hosts` on the machine where it is observed.  While the one you posted _should_ be reasonable, I don't have a sense of the before and after appearance in the cases of people who have fixed it.

**Comment by GaryWKeim** [comment]
Assuming "matc" is your machine name, you need to put that entry last:

    127.0.0.1	localhost
    255.255.255.255	broadcasthost
    ::1             localhost 
    127.0.0.1       matc.local

**Comment by mathieucarbou** [comment]
I did that @GaryWKeim :

```
➜  terracotta-platform git:(issue-178) ✗ cat /etc/hosts                           
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost 
127.0.0.1       matc.local
```

And I still have the same issue.

**Comment by mathieucarbou** [comment]
I needed to add both lines to make it work.

```
127.0.0.1       matc.local
::1             matc.local
```

**Comment by GaryWKeim** [comment]
OK, but I didn't do that and I don't have any problems.
