### ISSUE TITLE
connection.name not passed into PlatformConnectedClient

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/tc-passthrough-testing#6]
The connection name set when creating a connection is not passed to the PlatformConnectedClient.

Note: this is when using the `PassthroughConnectionService`: the properties object is not used at all. Perhaps it should be passed to `server.connectNewClient()` ?

**Comment by mathieucarbou** [comment]
@anthonydahanne : FYI, this blocks ehcache/ehcache3#1307

**Comment by jd0-sag** [comment]
Verified that this is only a problem in passthrough:  the multi-process server handles this as expected.  Working on a fix for this.
